version: '3.8'

services:
  icrogen-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: "${DATABASE_URL}"
      LOG_LEVEL: info
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    env_file:
      - .env

  # Optional: Adminer for database management (can connect to TiDB Cloud)
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000